create table tasks (
    id bigint generated by default as identity primary key,
    title varchar(100) not null,
    description text,
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint chk_tasks_status check (status in ('NEW', 'IN_PROGRESS', 'DONE', 'CANCELLED'))
);

create index idx_tasks_created_at_desc on tasks (created_at desc);
create index idx_tasks_status_created_at_desc on tasks (status, created_at desc);
